name: Python CI2

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Set python dependencies
        run: pip install -r requirements.txt -q && python ingest.py --device_type cpu
